apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=          # 'postgres' en base64
  DB_PASSWORD: MTIzNDU2          # '123456' en base64
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLWNsYXZlLWZlcnJldGVyaWEtdGVzdGluZy0yMDI2 # Clave secreta en base64